name: damast-test-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - matplotlib
  - numba
  - numpy
  - pip
  - jupyter-book
  - pip:
    - vaex
    - keras
    - scikit-learn
    - tensorflow
