# -----------------------------------------------------------
# DVC (Data Version Controller) parameters
#
# (C) 2020 Pierre Bernabé, Oslo, Norway
# email pierbernabe@simula.no
# -----------------------------------------------------------

data_processing:
  inputs:
    data:
      dir: "inputs/data"
    vessel_types: "inputs/data/mmsi_with_vesseltype.csv"
    # Data from the global fishing watch
    fishing_vessel_types: "inputs/data/fishing-vessels-v2.csv"
    # Anchorage locations
    anchorages: "inputs/data/anchorages.csv"
    # Satellite position data
    tle_file: "inputs/data/TLE_FILE.txt"
  outputs:
    processed:
      dir: "outputs/data_processing"
      h5_key: "data"
  MessageTypePosition: # https://gpsd.gitlab.io/gpsd/AIVDM.html
    - 1   # Position Report Class A
    - 2   # Position Report Class A (Assigned schedule)
    - 3   # Position Report Class A (Response to interrogation)
    - 9   # Standard SAR Aircraft Position Report
    - 18  # Standard Class B CS Position Report
    - 19  # Extended Class B Equipment Position Report
    - 21  # Position Report For Long-Range Applications
  columns:
    brut:
      - 'MMSI'
      - 'LON'
      - 'LAT'
      - 'BaseDateTime'
      - 'SOG'
      - 'COG'
      - 'Heading'
      - 'Status'
      - 'rot'
      - 'MessageType'
      - 'source'
    useless:
      - 'rot'
    unused:
      - 'MessageType'
      - 'source'
    constraints:
      MMSI:
        min: 200000000
        max: 799999999
        type: 'int32'
        default: 0
      LAT:
        min: -90
        max: 90
        type: 'float64'
        default: 0
      LON:
        min: -180
        max: 180
        type: 'float64'
        default: 0
      SOG:
        min: 0
        max: 1023
        type: 'int16'
        default: 1023
      COG:
        type: 'int16'
        default: 3600
      Status:
        type: 'int8'
        default: 0
      Heading:
        type: 'int16'
        default: 511
      timestamp:
        min: 1556064000
        max: 1559520000
        type: 'int32' # FIXME: This constraint does not seem sensible to be, as we shouldn't rescale the timestamp in data processing
      DISTDIFF:
        min: 0
        max: 20000
      SAT_DISTANCE:
        min: 600
        max: 10100

# ----------------------------------------------------------------
dataset_creation:
  inputs:
    data:
      dir: "outputs/data_processing"
      h5_key: "data"
  outputs:
    datasets:
      dir: "outputs/dataset_creation"
    combination_mapping: 'outputs/dataset_creation/combination_mapping.json'
  minimum_distance_port: 10
  windows: 51
  selected_fishing_type:
    "1": "drifting_longlines"
    "11": "set_longlines"
    "12": "squid_jigger"
    "13": "trawlers"
    "15": "tuna_purse_seines"
  selected_Status:
    "0": "Under way using engine"
    "1": "At anchor"
    "2": "Not under command"
    "3": "Restricted maneuverability"
    "4": "Constrained by her draught"
    "5": "Moored"
    "6": "Aground"
    "7": "Engaged in Fishing"
    "8": "Under way sailing"
  augment:
    # name of the feature column that will be created
    combination:
      from:
        fishing_type:
          type: vessel_types.VesselType
        Status:
          type: ais_navigational_status.AISNavigationalStatus
      # all other will be excluded
      include:
        fishing_type:
          - "drifting_longlines"
          - "set_longlines"
          - "squid_jigger"
          - "trawlers"
          - "tuna_purse_seines"
        Status:
          - 0 # "Under way using engine"
          - 1 # "At anchor"
          - 2 # "Not under command"
          - 3 # "Restricted maneuverability"
          - 4 # "Constrained by her draught"
          - 5 # "Moored"
          - 6 # "Aground"
          - 7 # "Engaged in Fishing"
          - 8 # "Under way sailing"
      # what to do with the columns
      operation: combine
      # intermediate output
      output: 'outputs/dataset_creation/combination_mapping.json'