name: Lint python package

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install pip
      run: python -m pip install -U pip

    - name: Install tox
      run: python -m pip install tox

    - name: Run linter
      run: tox -e lint

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: lint-codeclimate
        path: artifacts/lint/lint-codeclimate.json
        retention-days: 3
        overwrite: true


