name: Test python package

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install pip
        run: python -m pip install -U pip

      - name: Install package
        run: python -m pip install -e .[dev,test]

      - name: Install tox
        run: python -m pip install tox

      - name: Run tests
        run: tox -e py
