name: Test python package

on:
  push:
    paths:
      - tests/**
      - src/**
      - pyproject.toml
      - .github/workflows/test.yml
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        backend: ['torch','jax','tensorflow']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install os dependencies
        run: sudo apt update && sudo apt install -y graphviz

      - name: Install pip
        run: python -m pip install -U pip

      - name: Install package
        run: python -m pip install -e .[dev,test]

      # Run keras backend specific tests (for keras>=3)
      # Due to space issues avoid creating too many venvs (via tox)
      #     see https://github.com/actions/runner-images/issues/709
      - name: Run tests - ${{ matrix.backend }} backend
        run: KERAS_BACKEND=${{ matrix.backend }} pytest -v --timeout=120 --cov=damast --cov-report=term
