name: Publish to Zenodo

on:
  release:
    types: [published]

jobs:
  zenodo-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Archive repository
        run: git archive --format=zip HEAD -o release.zip

      - name: Upload to Zenodo
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            ZENODO_SANDBOX_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
            ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODO_TOKEN }}
        uses: zenodraft/action@0.13.3
        with:
          files: release.zip
          publish: false
          upsert-doi: true
          upsert-location: doi
          sandbox: true
